include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true

    prefer_double_quotes: true
    always_specify_types: false
    sort_child_properties_last: true
    use_full_hex_values_for_flutter_colors: true

    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_relative_lib_imports: true

    use_key_in_widget_constructors: true
    prefer_final_fields: true

    always_put_required_named_parameters_first: false