name: lechacals_authenticator
description: "A secure, open-source two-factor authentication app built from scratch"
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  otp: ^3.2.0
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^7.1.3
  vibration: ^3.1.4
  home_widget: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true