name: lechacals_authenticator
description: "An authenticator app inspired by Google Authenticator and made by LeChacal."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  otp: ^3.2.0
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true